all:
  timer:
    interval: 15
  spread_strategy:
    take_rate: 0.1
    take_increment: 0.2
    levels: 1
    default_size: 5
    price_threshold: 0.005
  depth_strategy:
    placement_depth: 10
    placement_interval: 0.001
    price_threshold: 0.0
    default_size: 0.1
